### ISSUE TITLE
where to find stuff

### ISSUE THREAD

**Issue by gilesbowkett** [pandastrike/garden#2] opened 2015-08-28 23:13 UTC
One thing I often run into is bafflement re where to find a Fairmont method. I'm looking for `pump`, and I'm looking for it because I don't remember what it does, so guessing which repo to look at, or which file within which repo, is kind of a hassle.

I'll probably solve this by creating a `fairmont` dir, checking all the Fairmont repos out in that dir, and then using [`ag`](https://github.com/ggreer/the_silver_searcher), but I feel like there should be a better way. Might even be overlooking the wiki here.

**Comment by dyoder** [comment] 2015-08-28 23:24
The wiki is supposed to be the right answer. Still a WIP tho:

https://github.com/pandastrike/fairmont/wiki/API-Reference#pump

**Comment by dyoder** [comment] 2018-09-07 04:14
breaking fairmont into a smaller libs. closing, altho technically that makes this problem worse. unless maybe it doesn't? because maybe the problem is thinking of them all as one giant library?

**Closed as completed by dyoder** 2018-09-07 04:14 UTC
